name: flutter_api
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  json_annotation: ^4.5.0
  connectivity_plus: ^2.3.5

dev_dependencies:
  json_serializable: ^6.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
flutter:
  uses-material-design: true
